export default [
  {
    city: "Abidjan",
    country: "Côte d'Ivoire",
    niceName: "Abidjan, Côte d'Ivoire",
    timezone: "Africa/Abidjan",
  },
  {
    city: "Accra",
    country: "Ghana",
    niceName: "Accra, Ghana",
    timezone: "Africa/Accra",
  },
  {
    city: "Addis Ababa",
    country: "Ethiopia",
    niceName: "Addis Ababa, Ethiopia",
    timezone: "Africa/Addis_Ababa",
  },
  {
    city: "Algiers",
    country: "Algeria",
    niceName: "Algiers, Algeria",
    timezone: "Africa/Algiers",
  },
  {
    city: "Asmara",
    country: "Eritrea",
    niceName: "Asmara, Eritrea",
    timezone: "Africa/Asmara",
  },
  {
    city: "Bamako",
    country: "Mali",
    niceName: "Bamako, Mali",
    timezone: "Africa/Bamako",
  },
  {
    city: "Bangui",
    country: "Central African Republic",
    niceName: "Bangui, Central African Republic",
    timezone: "Africa/Bangui",
  },
  {
    city: "Banjul",
    country: "Gambia",
    niceName: "Banjul, Gambia",
    timezone: "Africa/Banjul",
  },
  {
    city: "Bissau",
    country: "Guinea-Bissau",
    niceName: "Bissau, Guinea-Bissau",
    timezone: "Africa/Bissau",
  },
  {
    city: "Blantyre",
    country: "Malawi",
    niceName: "Blantyre, Malawi",
    timezone: "Africa/Blantyre",
  },
  {
    city: "Brazzaville",
    country: "Congo",
    niceName: "Brazzaville, Congo",
    timezone: "Africa/Brazzaville",
  },
  {
    city: "Bujumbura",
    country: "Burundi",
    niceName: "Bujumbura, Burundi",
    timezone: "Africa/Bujumbura",
  },
  {
    city: "Cairo",
    country: "Egypt",
    niceName: "Cairo, Egypt",
    timezone: "Africa/Cairo",
  },
  {
    city: "Casablanca",
    country: "Morocco",
    niceName: "Casablanca, Morocco",
    timezone: "Africa/Casablanca",
  },
  {
    city: "Ceuta",
    country: "Spain",
    niceName: "Ceuta, Spain",
    timezone: "Africa/Ceuta",
  },
  {
    city: "Conakry",
    country: "Guinea",
    niceName: "Conakry, Guinea",
    timezone: "Africa/Conakry",
  },
  {
    city: "Dakar",
    country: "Senegal",
    niceName: "Dakar, Senegal",
    timezone: "Africa/Dakar",
  },
  {
    city: "Dar es Salaam",
    country: "Tanzania",
    niceName: "Dar es Salaam, Tanzania",
    timezone: "Africa/Dar_es_Salaam",
  },
  {
    city: "Djibouti",
    country: "Djibouti",
    niceName: "Djibouti, Djibouti",
    timezone: "Africa/Djibouti",
  },
  {
    city: "Douala",
    country: "Cameroon",
    niceName: "Douala, Cameroon",
    timezone: "Africa/Douala",
  },
  {
    city: "El Aaiun",
    country: "Western Sahara",
    niceName: "El Aaiun, Western Sahara",
    timezone: "Africa/El_Aaiun",
  },
  {
    city: "Freetown",
    country: "Sierra Leone",
    niceName: "Freetown, Sierra Leone",
    timezone: "Africa/Freetown",
  },
  {
    city: "Gaborone",
    country: "Botswana",
    niceName: "Gaborone, Botswana",
    timezone: "Africa/Gaborone",
  },
  {
    city: "Harare",
    country: "Zimbabwe",
    niceName: "Harare, Zimbabwe",
    timezone: "Africa/Harare",
  },
  {
    city: "Johannesburg",
    country: "South Africa",
    niceName: "Johannesburg, South Africa",
    timezone: "Africa/Johannesburg",
  },
  {
    city: "Juba",
    country: "South Sudan",
    niceName: "Juba, South Sudan",
    timezone: "Africa/Juba",
  },
  {
    city: "Kampala",
    country: "Uganda",
    niceName: "Kampala, Uganda",
    timezone: "Africa/Kampala",
  },
  {
    city: "Khartoum",
    country: "Sudan",
    niceName: "Khartoum, Sudan",
    timezone: "Africa/Khartoum",
  },
  {
    city: "Kigali",
    country: "Rwanda",
    niceName: "Kigali, Rwanda",
    timezone: "Africa/Kigali",
  },
  {
    city: "Kinshasa",
    country: "Democratic Republic of the Congo",
    niceName: "Kinshasa, Democratic Republic of the Congo",
    timezone: "Africa/Kinshasa",
  },
  {
    city: "Lagos",
    country: "Nigeria",
    niceName: "Lagos, Nigeria",
    timezone: "Africa/Lagos",
  },
  {
    city: "Libreville",
    country: "Gabon",
    niceName: "Libreville, Gabon",
    timezone: "Africa/Libreville",
  },
  {
    city: "Lome",
    country: "Togo",
    niceName: "Lome, Togo",
    timezone: "Africa/Lome",
  },
  {
    city: "Luanda",
    country: "Angola",
    niceName: "Luanda, Angola",
    timezone: "Africa/Luanda",
  },
  {
    city: "Lubumbashi",
    country: "Democratic Republic of the Congo",
    niceName: "Lubumbashi, Democratic Republic of the Congo",
    timezone: "Africa/Lubumbashi",
  },
  {
    city: "Lusaka",
    country: "Zambia",
    niceName: "Lusaka, Zambia",
    timezone: "Africa/Lusaka",
  },
  {
    city: "Malabo",
    country: "Equatorial Guinea",
    niceName: "Malabo, Equatorial Guinea",
    timezone: "Africa/Malabo",
  },
  {
    city: "Maputo",
    country: "Mozambique",
    niceName: "Maputo, Mozambique",
    timezone: "Africa/Maputo",
  },
  {
    city: "Maseru",
    country: "Lesotho",
    niceName: "Maseru, Lesotho",
    timezone: "Africa/Maseru",
  },
  {
    city: "Mbabane",
    country: "Eswatini",
    niceName: "Mbabane, Eswatini",
    timezone: "Africa/Mbabane",
  },
  {
    city: "Mogadishu",
    country: "Somalia",
    niceName: "Mogadishu, Somalia",
    timezone: "Africa/Mogadishu",
  },
  {
    city: "Monrovia",
    country: "Liberia",
    niceName: "Monrovia, Liberia",
    timezone: "Africa/Monrovia",
  },
  {
    city: "Nairobi",
    country: "Kenya",
    niceName: "Nairobi, Kenya",
    timezone: "Africa/Nairobi",
  },
  {
    city: "Ndjamena",
    country: "Chad",
    niceName: "Ndjamena, Chad",
    timezone: "Africa/Ndjamena",
  },
  {
    city: "Niamey",
    country: "Niger",
    niceName: "Niamey, Niger",
    timezone: "Africa/Niamey",
  },
  {
    city: "Nouakchott",
    country: "Mauritania",
    niceName: "Nouakchott, Mauritania",
    timezone: "Africa/Nouakchott",
  },
  {
    city: "Ouagadougou",
    country: "Burkina Faso",
    niceName: "Ouagadougou, Burkina Faso",
    timezone: "Africa/Ouagadougou",
  },
  {
    city: "Porto-Novo",
    country: "Benin",
    niceName: "Porto-Novo, Benin",
    timezone: "Africa/Porto-Novo",
  },
  {
    city: "Sao Tome",
    country: "Sao Tome and Principe",
    niceName: "Sao Tome, Sao Tome and Principe",
    timezone: "Africa/Sao_Tome",
  },
  {
    city: "Timbuktu",
    country: "Mali",
    niceName: "Timbuktu, Mali",
    timezone: "Africa/Timbuktu",
  },
  {
    city: "Tripoli",
    country: "Libya",
    niceName: "Tripoli, Libya",
    timezone: "Africa/Tripoli",
  },
  {
    city: "Tunis",
    country: "Tunisia",
    niceName: "Tunis, Tunisia",
    timezone: "Africa/Tunis",
  },
  {
    city: "Windhoek",
    country: "Namibia",
    niceName: "Windhoek, Namibia",
    timezone: "Africa/Windhoek",
  },
  {
    city: "Adak",
    country: "United States of America",
    niceName: "Adak, United States of America",
    timezone: "America/Adak",
  },
  {
    city: "Anchorage",
    country: "United States of America",
    niceName: "Anchorage, United States of America",
    timezone: "America/Anchorage",
  },
  {
    city: "Anguilla",
    country: "Anguilla",
    niceName: "Anguilla, Anguilla",
    timezone: "America/Anguilla",
  },
  {
    city: "Antigua",
    country: "Antigua and Barbuda",
    niceName: "Antigua, Antigua and Barbuda",
    timezone: "America/Antigua",
  },
  {
    city: "Araguaina",
    country: "Brazil",
    niceName: "Araguaina, Brazil",
    timezone: "America/Araguaina",
  },
  {
    city: "Buenos Aires",
    country: "Argentina",
    niceName: "Buenos Aires, Argentina",
    timezone: "America/Argentina/Buenos_Aires",
  },
  {
    city: "Catamarca",
    country: "Argentina",
    niceName: "Catamarca, Argentina",
    timezone: "America/Argentina/Catamarca",
  },
  {
    city: "Cordoba",
    country: "Argentina",
    niceName: "Cordoba, Argentina",
    timezone: "America/Argentina/Cordoba",
  },
  {
    city: "Jujuy",
    country: "Argentina",
    niceName: "Jujuy, Argentina",
    timezone: "America/Argentina/Jujuy",
  },
  {
    city: "La Rioja",
    country: "Argentina",
    niceName: "La Rioja, Argentina",
    timezone: "America/Argentina/La_Rioja",
  },
  {
    city: "Mendoza",
    country: "Argentina",
    niceName: "Mendoza, Argentina",
    timezone: "America/Argentina/Mendoza",
  },
  {
    city: "Rio Gallegos",
    country: "Argentina",
    niceName: "Rio Gallegos, Argentina",
    timezone: "America/Argentina/Rio_Gallegos",
  },
  {
    city: "Salta",
    country: "Argentina",
    niceName: "Salta, Argentina",
    timezone: "America/Argentina/Salta",
  },
  {
    city: "San Juan",
    country: "Argentina",
    niceName: "San Juan, Argentina",
    timezone: "America/Argentina/San_Juan",
  },
  {
    city: "San Luis",
    country: "Argentina",
    niceName: "San Luis, Argentina",
    timezone: "America/Argentina/San_Luis",
  },
  {
    city: "Tucuman",
    country: "Argentina",
    niceName: "Tucuman, Argentina",
    timezone: "America/Argentina/Tucuman",
  },
  {
    city: "Ushuaia",
    country: "Argentina",
    niceName: "Ushuaia, Argentina",
    timezone: "America/Argentina/Ushuaia",
  },
  {
    city: "Aruba",
    country: "Aruba",
    niceName: "Aruba, Aruba",
    timezone: "America/Aruba",
  },
  {
    city: "Asuncion",
    country: "Paraguay",
    niceName: "Asuncion, Paraguay",
    timezone: "America/Asuncion",
  },
  {
    city: "Atikokan",
    country: "Canada",
    niceName: "Atikokan, Canada",
    timezone: "America/Atikokan",
  },
  {
    city: "Atka",
    country: "United States of America",
    niceName: "Atka, United States of America",
    timezone: "America/Atka",
  },
  {
    city: "Bahia",
    country: "Brazil",
    niceName: "Bahia, Brazil",
    timezone: "America/Bahia",
  },
  {
    city: "Bahia Banderas",
    country: "Mexico",
    niceName: "Bahia Banderas, Mexico",
    timezone: "America/Bahia_Banderas",
  },
  {
    city: "Barbados",
    country: "Barbados",
    niceName: "Barbados, Barbados",
    timezone: "America/Barbados",
  },
  {
    city: "Belem",
    country: "Brazil",
    niceName: "Belem, Brazil",
    timezone: "America/Belem",
  },
  {
    city: "Belize",
    country: "Belize",
    niceName: "Belize, Belize",
    timezone: "America/Belize",
  },
  {
    city: "Blanc-Sablon",
    country: "Canada",
    niceName: "Blanc-Sablon, Canada",
    timezone: "America/Blanc-Sablon",
  },
  {
    city: "Boa Vista",
    country: "Brazil",
    niceName: "Boa Vista, Brazil",
    timezone: "America/Boa_Vista",
  },
  {
    city: "Bogota",
    country: "Colombia",
    niceName: "Bogota, Colombia",
    timezone: "America/Bogota",
  },
  {
    city: "Boise",
    country: "United States of America",
    niceName: "Boise, United States of America",
    timezone: "America/Boise",
  },
  {
    city: "Cambridge Bay",
    country: "Canada",
    niceName: "Cambridge Bay, Canada",
    timezone: "America/Cambridge_Bay",
  },
  {
    city: "Campo Grande",
    country: "Brazil",
    niceName: "Campo Grande, Brazil",
    timezone: "America/Campo_Grande",
  },
  {
    city: "Cancun",
    country: "Mexico",
    niceName: "Cancun, Mexico",
    timezone: "America/Cancun",
  },
  {
    city: "Caracas",
    country: "Venezuela",
    niceName: "Caracas, Venezuela",
    timezone: "America/Caracas",
  },
  {
    city: "Cayenne",
    country: "French Guiana",
    niceName: "Cayenne, French Guiana",
    timezone: "America/Cayenne",
  },
  {
    city: "Cayman",
    country: "Cayman Islands",
    niceName: "Cayman, Cayman Islands",
    timezone: "America/Cayman",
  },
  {
    city: "Chicago",
    country: "United States of America",
    niceName: "Chicago, United States of America",
    timezone: "America/Chicago",
  },
  {
    city: "Chihuahua",
    country: "Mexico",
    niceName: "Chihuahua, Mexico",
    timezone: "America/Chihuahua",
  },
  {
    city: "Coral Harbour",
    country: "Canada",
    niceName: "Coral Harbour, Canada",
    timezone: "America/Coral_Harbour",
  },
  {
    city: "Costa Rica",
    country: "Costa Rica",
    niceName: "Costa Rica, Costa Rica",
    timezone: "America/Costa_Rica",
  },
  {
    city: "Creston",
    country: "Canada",
    niceName: "Creston, Canada",
    timezone: "America/Creston",
  },
  {
    city: "Cuiaba",
    country: "Brazil",
    niceName: "Cuiaba, Brazil",
    timezone: "America/Cuiaba",
  },
  {
    city: "Curacao",
    country: "Curaçao",
    niceName: "Curacao, Curaçao",
    timezone: "America/Curacao",
  },
  {
    city: "Danmarkshavn",
    country: "Greenland",
    niceName: "Danmarkshavn, Greenland",
    timezone: "America/Danmarkshavn",
  },
  {
    city: "Dawson",
    country: "Canada",
    niceName: "Dawson, Canada",
    timezone: "America/Dawson",
  },
  {
    city: "Dawson Creek",
    country: "Canada",
    niceName: "Dawson Creek, Canada",
    timezone: "America/Dawson_Creek",
  },
  {
    city: "Denver",
    country: "United States of America",
    niceName: "Denver, United States of America",
    timezone: "America/Denver",
  },
  {
    city: "Detroit",
    country: "United States of America",
    niceName: "Detroit, United States of America",
    timezone: "America/Detroit",
  },
  {
    city: "Dominica",
    country: "Dominica",
    niceName: "Dominica, Dominica",
    timezone: "America/Dominica",
  },
  {
    city: "Edmonton",
    country: "Canada",
    niceName: "Edmonton, Canada",
    timezone: "America/Edmonton",
  },
  {
    city: "Eirunepe",
    country: "Brazil",
    niceName: "Eirunepe, Brazil",
    timezone: "America/Eirunepe",
  },
  {
    city: "El Salvador",
    country: "El Salvador",
    niceName: "El Salvador, El Salvador",
    timezone: "America/El_Salvador",
  },
  {
    city: "Ensenada",
    country: "Mexico",
    niceName: "Ensenada, Mexico",
    timezone: "America/Ensenada",
  },
  {
    city: "Fort Nelson",
    country: "Canada",
    niceName: "Fort Nelson, Canada",
    timezone: "America/Fort_Nelson",
  },
  {
    city: "Fort Wayne",
    country: "United States of America",
    niceName: "Fort Wayne, United States of America",
    timezone: "America/Fort_Wayne",
  },
  {
    city: "Fortaleza",
    country: "Brazil",
    niceName: "Fortaleza, Brazil",
    timezone: "America/Fortaleza",
  },
  {
    city: "Glace Bay",
    country: "Canada",
    niceName: "Glace Bay, Canada",
    timezone: "America/Glace_Bay",
  },
  {
    city: "Godthab",
    country: "Greenland",
    niceName: "Godthab, Greenland",
    timezone: "America/Godthab",
  },
  {
    city: "Goose Bay",
    country: "Canada",
    niceName: "Goose Bay, Canada",
    timezone: "America/Goose_Bay",
  },
  {
    city: "Grand Turk",
    country: "Turks and Caicos Islands",
    niceName: "Grand Turk, Turks and Caicos Islands",
    timezone: "America/Grand_Turk",
  },
  {
    city: "Grenada",
    country: "Grenada",
    niceName: "Grenada, Grenada",
    timezone: "America/Grenada",
  },
  {
    city: "Guadeloupe",
    country: "Guadeloupe",
    niceName: "Guadeloupe, Guadeloupe",
    timezone: "America/Guadeloupe",
  },
  {
    city: "Guatemala",
    country: "Guatemala",
    niceName: "Guatemala, Guatemala",
    timezone: "America/Guatemala",
  },
  {
    city: "Guayaquil",
    country: "Ecuador",
    niceName: "Guayaquil, Ecuador",
    timezone: "America/Guayaquil",
  },
  {
    city: "Guyana",
    country: "Guyana",
    niceName: "Guyana, Guyana",
    timezone: "America/Guyana",
  },
  {
    city: "Halifax",
    country: "Canada",
    niceName: "Halifax, Canada",
    timezone: "America/Halifax",
  },
  {
    city: "Havana",
    country: "Cuba",
    niceName: "Havana, Cuba",
    timezone: "America/Havana",
  },
  {
    city: "Hermosillo",
    country: "Mexico",
    niceName: "Hermosillo, Mexico",
    timezone: "America/Hermosillo",
  },
  {
    city: "Knox",
    country: "United States of America",
    niceName: "Knox, United States of America",
    timezone: "America/Indiana/Knox",
  },
  {
    city: "Marengo",
    country: "United States of America",
    niceName: "Marengo, United States of America",
    timezone: "America/Indiana/Marengo",
  },
  {
    city: "Petersburg",
    country: "United States of America",
    niceName: "Petersburg, United States of America",
    timezone: "America/Indiana/Petersburg",
  },
  {
    city: "Tell City",
    country: "United States of America",
    niceName: "Tell City, United States of America",
    timezone: "America/Indiana/Tell_City",
  },
  {
    city: "Vevay",
    country: "United States of America",
    niceName: "Vevay, United States of America",
    timezone: "America/Indiana/Vevay",
  },
  {
    city: "Vincennes",
    country: "United States of America",
    niceName: "Vincennes, United States of America",
    timezone: "America/Indiana/Vincennes",
  },
  {
    city: "Winamac",
    country: "United States of America",
    niceName: "Winamac, United States of America",
    timezone: "America/Indiana/Winamac",
  },
  {
    city: "Indianapolis",
    country: "United States of America",
    niceName: "Indianapolis, United States of America",
    timezone: "America/Indianapolis",
  },
  {
    city: "Inuvik",
    country: "Canada",
    niceName: "Inuvik, Canada",
    timezone: "America/Inuvik",
  },
  {
    city: "Iqaluit",
    country: "Canada",
    niceName: "Iqaluit, Canada",
    timezone: "America/Iqaluit",
  },
  {
    city: "Jamaica",
    country: "Jamaica",
    niceName: "Jamaica, Jamaica",
    timezone: "America/Jamaica",
  },
  {
    city: "Juneau",
    country: "United States of America",
    niceName: "Juneau, United States of America",
    timezone: "America/Juneau",
  },
  {
    city: "Louisville",
    country: "United States of America",
    niceName: "Louisville, United States of America",
    timezone: "America/Kentucky/Louisville",
  },
  {
    city: "Monticello",
    country: "United States of America",
    niceName: "Monticello, United States of America",
    timezone: "America/Kentucky/Monticello",
  },
  {
    city: "Kralendijk",
    country: "Bonaire, Sint Eustatius and Saba",
    niceName: "Kralendijk, Bonaire, Sint Eustatius and Saba",
    timezone: "America/Kralendijk",
  },
  {
    city: "La Paz",
    country: "Bolivia",
    niceName: "La Paz, Bolivia",
    timezone: "America/La_Paz",
  },
  {
    city: "Lima",
    country: "Peru",
    niceName: "Lima, Peru",
    timezone: "America/Lima",
  },
  {
    city: "Los Angeles",
    country: "United States of America",
    niceName: "Los Angeles, United States of America",
    timezone: "America/Los_Angeles",
  },
  {
    city: "Lower Princes",
    country: "Sint Maarten (Dutch part)",
    niceName: "Lower Princes, Sint Maarten (Dutch part)",
    timezone: "America/Lower_Princes",
  },
  {
    city: "Maceio",
    country: "Brazil",
    niceName: "Maceio, Brazil",
    timezone: "America/Maceio",
  },
  {
    city: "Managua",
    country: "Nicaragua",
    niceName: "Managua, Nicaragua",
    timezone: "America/Managua",
  },
  {
    city: "Manaus",
    country: "Brazil",
    niceName: "Manaus, Brazil",
    timezone: "America/Manaus",
  },
  {
    city: "Marigot",
    country: "Saint Martin (French part)",
    niceName: "Marigot, Saint Martin (French part)",
    timezone: "America/Marigot",
  },
  {
    city: "Martinique",
    country: "Martinique",
    niceName: "Martinique, Martinique",
    timezone: "America/Martinique",
  },
  {
    city: "Matamoros",
    country: "Mexico",
    niceName: "Matamoros, Mexico",
    timezone: "America/Matamoros",
  },
  {
    city: "Mazatlan",
    country: "Mexico",
    niceName: "Mazatlan, Mexico",
    timezone: "America/Mazatlan",
  },
  {
    city: "Menominee",
    country: "United States of America",
    niceName: "Menominee, United States of America",
    timezone: "America/Menominee",
  },
  {
    city: "Merida",
    country: "Mexico",
    niceName: "Merida, Mexico",
    timezone: "America/Merida",
  },
  {
    city: "Metlakatla",
    country: "United States of America",
    niceName: "Metlakatla, United States of America",
    timezone: "America/Metlakatla",
  },
  {
    city: "Mexico City",
    country: "Mexico",
    niceName: "Mexico City, Mexico",
    timezone: "America/Mexico_City",
  },
  {
    city: "Miquelon",
    country: "Saint Pierre and Miquelon",
    niceName: "Miquelon, Saint Pierre and Miquelon",
    timezone: "America/Miquelon",
  },
  {
    city: "Moncton",
    country: "Canada",
    niceName: "Moncton, Canada",
    timezone: "America/Moncton",
  },
  {
    city: "Monterrey",
    country: "Mexico",
    niceName: "Monterrey, Mexico",
    timezone: "America/Monterrey",
  },
  {
    city: "Montevideo",
    country: "Uruguay",
    niceName: "Montevideo, Uruguay",
    timezone: "America/Montevideo",
  },
  {
    city: "Montreal",
    country: "Canada",
    niceName: "Montreal, Canada",
    timezone: "America/Montreal",
  },
  {
    city: "Montserrat",
    country: "Montserrat",
    niceName: "Montserrat, Montserrat",
    timezone: "America/Montserrat",
  },
  {
    city: "Nassau",
    country: "Bahamas",
    niceName: "Nassau, Bahamas",
    timezone: "America/Nassau",
  },
  {
    city: "New York",
    country: "United States of America",
    niceName: "New York, United States of America",
    timezone: "America/New_York",
  },
  {
    city: "Nipigon",
    country: "Canada",
    niceName: "Nipigon, Canada",
    timezone: "America/Nipigon",
  },
  {
    city: "Nome",
    country: "United States of America",
    niceName: "Nome, United States of America",
    timezone: "America/Nome",
  },
  {
    city: "Noronha",
    country: "Brazil",
    niceName: "Noronha, Brazil",
    timezone: "America/Noronha",
  },
  {
    city: "Beulah",
    country: "United States of America",
    niceName: "Beulah, United States of America",
    timezone: "America/North_Dakota/Beulah",
  },
  {
    city: "Center",
    country: "United States of America",
    niceName: "Center, United States of America",
    timezone: "America/North_Dakota/Center",
  },
  {
    city: "New Salem",
    country: "United States of America",
    niceName: "New Salem, United States of America",
    timezone: "America/North_Dakota/New_Salem",
  },
  {
    city: "Ojinaga",
    country: "Mexico",
    niceName: "Ojinaga, Mexico",
    timezone: "America/Ojinaga",
  },
  {
    city: "Panama",
    country: "Panama",
    niceName: "Panama, Panama",
    timezone: "America/Panama",
  },
  {
    city: "Pangnirtung",
    country: "Canada",
    niceName: "Pangnirtung, Canada",
    timezone: "America/Pangnirtung",
  },
  {
    city: "Paramaribo",
    country: "Suriname",
    niceName: "Paramaribo, Suriname",
    timezone: "America/Paramaribo",
  },
  {
    city: "Phoenix",
    country: "United States of America",
    niceName: "Phoenix, United States of America",
    timezone: "America/Phoenix",
  },
  {
    city: "Port of Spain",
    country: "Trinidad and Tobago",
    niceName: "Port of Spain, Trinidad and Tobago",
    timezone: "America/Port_of_Spain",
  },
  {
    city: "Port-au-Prince",
    country: "Haiti",
    niceName: "Port-au-Prince, Haiti",
    timezone: "America/Port-au-Prince",
  },
  {
    city: "Porto Acre",
    country: "Brazil",
    niceName: "Porto Acre, Brazil",
    timezone: "America/Porto_Acre",
  },
  {
    city: "Porto Velho",
    country: "Brazil",
    niceName: "Porto Velho, Brazil",
    timezone: "America/Porto_Velho",
  },
  {
    city: "Puerto Rico",
    country: "Puerto Rico",
    niceName: "Puerto Rico, Puerto Rico",
    timezone: "America/Puerto_Rico",
  },
  {
    city: "Punta Arenas",
    country: "Chile",
    niceName: "Punta Arenas, Chile",
    timezone: "America/Punta_Arenas",
  },
  {
    city: "Rainy River",
    country: "Canada",
    niceName: "Rainy River, Canada",
    timezone: "America/Rainy_River",
  },
  {
    city: "Rankin Inlet",
    country: "Canada",
    niceName: "Rankin Inlet, Canada",
    timezone: "America/Rankin_Inlet",
  },
  {
    city: "Recife",
    country: "Brazil",
    niceName: "Recife, Brazil",
    timezone: "America/Recife",
  },
  {
    city: "Regina",
    country: "Canada",
    niceName: "Regina, Canada",
    timezone: "America/Regina",
  },
  {
    city: "Resolute",
    country: "Canada",
    niceName: "Resolute, Canada",
    timezone: "America/Resolute",
  },
  {
    city: "Rio Branco",
    country: "Brazil",
    niceName: "Rio Branco, Brazil",
    timezone: "America/Rio_Branco",
  },
  {
    city: "Rosario",
    country: "Argentina",
    niceName: "Rosario, Argentina",
    timezone: "America/Rosario",
  },
  {
    city: "Santa Isabel",
    country: "Puerto Rico",
    niceName: "Santa Isabel, Puerto Rico",
    timezone: "America/Santa_Isabel",
  },
  {
    city: "Santarem",
    country: "Brazil",
    niceName: "Santarem, Brazil",
    timezone: "America/Santarem",
  },
  {
    city: "Santiago",
    country: "Chile",
    niceName: "Santiago, Chile",
    timezone: "America/Santiago",
  },
  {
    city: "Santo Domingo",
    country: "Dominican Republic",
    niceName: "Santo Domingo, Dominican Republic",
    timezone: "America/Santo_Domingo",
  },
  {
    city: "Sao Paulo",
    country: "Brazil",
    niceName: "Sao Paulo, Brazil",
    timezone: "America/Sao_Paulo",
  },
  {
    city: "Scoresbysund",
    country: "Greenland",
    niceName: "Scoresbysund, Greenland",
    timezone: "America/Scoresbysund",
  },
  {
    city: "Shiprock",
    country: "United States of America",
    niceName: "Shiprock, United States of America",
    timezone: "America/Shiprock",
  },
  {
    city: "Sitka",
    country: "United States of America",
    niceName: "Sitka, United States of America",
    timezone: "America/Sitka",
  },
  {
    city: "St Barthelemy",
    country: "Saint Barthélemy",
    niceName: "St Barthelemy, Saint Barthélemy",
    timezone: "America/St_Barthelemy",
  },
  {
    city: "St Johns",
    country: "Canada",
    niceName: "St Johns, Canada",
    timezone: "America/St_Johns",
  },
  {
    city: "St Kitts",
    country: "Saint Kitts and Nevis",
    niceName: "St Kitts, Saint Kitts and Nevis",
    timezone: "America/St_Kitts",
  },
  {
    city: "St Lucia",
    country: "Saint Lucia",
    niceName: "St Lucia, Saint Lucia",
    timezone: "America/St_Lucia",
  },
  {
    city: "St Thomas",
    country: "Virgin Islands (U.S.)",
    niceName: "St Thomas, Virgin Islands (U.S.)",
    timezone: "America/St_Thomas",
  },
  {
    city: "St Vincent",
    country: "Saint Vincent and the Grenadines",
    niceName: "St Vincent, Saint Vincent and the Grenadines",
    timezone: "America/St_Vincent",
  },
  {
    city: "Swift Current",
    country: "Canada",
    niceName: "Swift Current, Canada",
    timezone: "America/Swift_Current",
  },
  {
    city: "Tegucigalpa",
    country: "Honduras",
    niceName: "Tegucigalpa, Honduras",
    timezone: "America/Tegucigalpa",
  },
  {
    city: "Thule",
    country: "Greenland",
    niceName: "Thule, Greenland",
    timezone: "America/Thule",
  },
  {
    city: "Thunder Bay",
    country: "Canada",
    niceName: "Thunder Bay, Canada",
    timezone: "America/Thunder_Bay",
  },
  {
    city: "Tijuana",
    country: "Mexico",
    niceName: "Tijuana, Mexico",
    timezone: "America/Tijuana",
  },
  {
    city: "Toronto",
    country: "Canada",
    niceName: "Toronto, Canada",
    timezone: "America/Toronto",
  },
  {
    city: "Tortola",
    country: "British Virgin Islands",
    niceName: "Tortola, British Virgin Islands",
    timezone: "America/Tortola",
  },
  {
    city: "Vancouver",
    country: "Canada",
    niceName: "Vancouver, Canada",
    timezone: "America/Vancouver",
  },
  {
    city: "Whitehorse",
    country: "Canada",
    niceName: "Whitehorse, Canada",
    timezone: "America/Whitehorse",
  },
  {
    city: "Winnipeg",
    country: "Canada",
    niceName: "Winnipeg, Canada",
    timezone: "America/Winnipeg",
  },
  {
    city: "Yakutat",
    country: "United States of America",
    niceName: "Yakutat, United States of America",
    timezone: "America/Yakutat",
  },
  {
    city: "Yellowknife",
    country: "Canada",
    niceName: "Yellowknife, Canada",
    timezone: "America/Yellowknife",
  },
  {
    city: "Casey",
    country: "Antarctica",
    niceName: "Casey, Antarctica",
    timezone: "Antarctica/Casey",
  },
  {
    city: "Davis",
    country: "Antarctica",
    niceName: "Davis, Antarctica",
    timezone: "Antarctica/Davis",
  },
  {
    city: "Macquarie",
    country: "Australia",
    niceName: "Macquarie, Australia",
    timezone: "Antarctica/Macquarie",
  },
  {
    city: "Mawson",
    country: "Antarctica",
    niceName: "Mawson, Antarctica",
    timezone: "Antarctica/Mawson",
  },
  {
    city: "Palmer",
    country: "Antarctica",
    niceName: "Palmer, Antarctica",
    timezone: "Antarctica/Palmer",
  },
  {
    city: "Rothera",
    country: "Antarctica",
    niceName: "Rothera, Antarctica",
    timezone: "Antarctica/Rothera",
  },
  {
    city: "South Pole",
    country: "Antarctica",
    niceName: "South Pole, Antarctica",
    timezone: "Antarctica/South_Pole",
  },
  {
    city: "Syowa",
    country: "Antarctica",
    niceName: "Syowa, Antarctica",
    timezone: "Antarctica/Syowa",
  },
  {
    city: "Troll",
    country: "Antarctica",
    niceName: "Troll, Antarctica",
    timezone: "Antarctica/Troll",
  },
  {
    city: "Vostok",
    country: "Antarctica",
    niceName: "Vostok, Antarctica",
    timezone: "Antarctica/Vostok",
  },
  {
    city: "Longyearbyen",
    country: "Svalbard and Jan Mayen",
    niceName: "Longyearbyen, Svalbard and Jan Mayen",
    timezone: "Arctic/Longyearbyen",
  },
  {
    city: "Aden",
    country: "Yemen",
    niceName: "Aden, Yemen",
    timezone: "Asia/Aden",
  },
  {
    city: "Almaty",
    country: "Kazakhstan",
    niceName: "Almaty, Kazakhstan",
    timezone: "Asia/Almaty",
  },
  {
    city: "Amman",
    country: "Jordan",
    niceName: "Amman, Jordan",
    timezone: "Asia/Amman",
  },
  {
    city: "Anadyr",
    country: "Russia",
    niceName: "Anadyr, Russia",
    timezone: "Asia/Anadyr",
  },
  {
    city: "Aqtau",
    country: "Kazakhstan",
    niceName: "Aqtau, Kazakhstan",
    timezone: "Asia/Aqtau",
  },
  {
    city: "Aqtobe",
    country: "Kazakhstan",
    niceName: "Aqtobe, Kazakhstan",
    timezone: "Asia/Aqtobe",
  },
  {
    city: "Ashgabat",
    country: "Turkmenistan",
    niceName: "Ashgabat, Turkmenistan",
    timezone: "Asia/Ashgabat",
  },
  {
    city: "Ashkhabad",
    country: "Turkmenistan",
    niceName: "Ashkhabad, Turkmenistan",
    timezone: "Asia/Ashkhabad",
  },
  {
    city: "Atyrau",
    country: "Kazakhstan",
    niceName: "Atyrau, Kazakhstan",
    timezone: "Asia/Atyrau",
  },
  {
    city: "Baghdad",
    country: "Iraq",
    niceName: "Baghdad, Iraq",
    timezone: "Asia/Baghdad",
  },
  {
    city: "Bahrain",
    country: "Bahrain",
    niceName: "Bahrain, Bahrain",
    timezone: "Asia/Bahrain",
  },
  {
    city: "Baku",
    country: "Azerbaijan",
    niceName: "Baku, Azerbaijan",
    timezone: "Asia/Baku",
  },
  {
    city: "Bangkok",
    country: "Thailand",
    niceName: "Bangkok, Thailand",
    timezone: "Asia/Bangkok",
  },
  {
    city: "Barnaul",
    country: "Russia",
    niceName: "Barnaul, Russia",
    timezone: "Asia/Barnaul",
  },
  {
    city: "Beirut",
    country: "Lebanon",
    niceName: "Beirut, Lebanon",
    timezone: "Asia/Beirut",
  },
  {
    city: "Bishkek",
    country: "Kyrgyzstan",
    niceName: "Bishkek, Kyrgyzstan",
    timezone: "Asia/Bishkek",
  },
  {
    city: "Brunei",
    country: "Brunei",
    niceName: "Brunei, Brunei",
    timezone: "Asia/Brunei",
  },
  {
    city: "Calcutta",
    country: "India",
    niceName: "Calcutta, India",
    timezone: "Asia/Calcutta",
  },
  {
    city: "Chita",
    country: "Russia",
    niceName: "Chita, Russia",
    timezone: "Asia/Chita",
  },
  {
    city: "Choibalsan",
    country: "Mongolia",
    niceName: "Choibalsan, Mongolia",
    timezone: "Asia/Choibalsan",
  },
  {
    city: "Chongqing",
    country: "China",
    niceName: "Chongqing, China",
    timezone: "Asia/Chongqing",
  },
  {
    city: "Chungking",
    country: "China",
    niceName: "Chungking, China",
    timezone: "Asia/Chungking",
  },
  {
    city: "Colombo",
    country: "Sri Lanka",
    niceName: "Colombo, Sri Lanka",
    timezone: "Asia/Colombo",
  },
  {
    city: "Dacca",
    country: "Bangladesh",
    niceName: "Dacca, Bangladesh",
    timezone: "Asia/Dacca",
  },
  {
    city: "Damascus",
    country: "Syria",
    niceName: "Damascus, Syria",
    timezone: "Asia/Damascus",
  },
  {
    city: "Dhaka",
    country: "Bangladesh",
    niceName: "Dhaka, Bangladesh",
    timezone: "Asia/Dhaka",
  },
  {
    city: "Dili",
    country: "Timor-Leste",
    niceName: "Dili, Timor-Leste",
    timezone: "Asia/Dili",
  },
  {
    city: "Dubai",
    country: "United Arab Emirates",
    niceName: "Dubai, United Arab Emirates",
    timezone: "Asia/Dubai",
  },
  {
    city: "Dushanbe",
    country: "Tajikistan",
    niceName: "Dushanbe, Tajikistan",
    timezone: "Asia/Dushanbe",
  },
  {
    city: "Famagusta",
    country: "Cyprus",
    niceName: "Famagusta, Cyprus",
    timezone: "Asia/Famagusta",
  },
  {
    city: "Gaza",
    country: "Palestine",
    niceName: "Gaza, Palestine",
    timezone: "Asia/Gaza",
  },
  {
    city: "Harbin",
    country: "China",
    niceName: "Harbin, China",
    timezone: "Asia/Harbin",
  },
  {
    city: "Hebron",
    country: "Palestine",
    niceName: "Hebron, Palestine",
    timezone: "Asia/Hebron",
  },
  {
    city: "Ho Chi Minh",
    country: "Viet Nam",
    niceName: "Ho Chi Minh, Viet Nam",
    timezone: "Asia/Ho_Chi_Minh",
  },
  {
    city: "Hong Kong",
    country: "Hong Kong",
    niceName: "Hong Kong, Hong Kong",
    timezone: "Asia/Hong_Kong",
  },
  {
    city: "Hovd",
    country: "Mongolia",
    niceName: "Hovd, Mongolia",
    timezone: "Asia/Hovd",
  },
  {
    city: "Irkutsk",
    country: "Russia",
    niceName: "Irkutsk, Russia",
    timezone: "Asia/Irkutsk",
  },
  {
    city: "Istanbul",
    country: "Turkey",
    niceName: "Istanbul, Turkey",
    timezone: "Asia/Istanbul",
  },
  {
    city: "Jakarta",
    country: "Indonesia",
    niceName: "Jakarta, Indonesia",
    timezone: "Asia/Jakarta",
  },
  {
    city: "Jayapura",
    country: "Indonesia",
    niceName: "Jayapura, Indonesia",
    timezone: "Asia/Jayapura",
  },
  {
    city: "Jerusalem",
    country: "Israel",
    niceName: "Jerusalem, Israel",
    timezone: "Asia/Jerusalem",
  },
  {
    city: "Kabul",
    country: "Afghanistan",
    niceName: "Kabul, Afghanistan",
    timezone: "Asia/Kabul",
  },
  {
    city: "Kamchatka",
    country: "Russia",
    niceName: "Kamchatka, Russia",
    timezone: "Asia/Kamchatka",
  },
  {
    city: "Karachi",
    country: "Pakistan",
    niceName: "Karachi, Pakistan",
    timezone: "Asia/Karachi",
  },
  {
    city: "Kashgar",
    country: "China",
    niceName: "Kashgar, China",
    timezone: "Asia/Kashgar",
  },
  {
    city: "Kathmandu",
    country: "Nepal",
    niceName: "Kathmandu, Nepal",
    timezone: "Asia/Kathmandu",
  },
  {
    city: "Katmandu",
    country: "Nepal",
    niceName: "Katmandu, Nepal",
    timezone: "Asia/Katmandu",
  },
  {
    city: "Khandyga",
    country: "Russia",
    niceName: "Khandyga, Russia",
    timezone: "Asia/Khandyga",
  },
  {
    city: "Kolkata",
    country: "India",
    niceName: "Kolkata, India",
    timezone: "Asia/Kolkata",
  },
  {
    city: "Krasnoyarsk",
    country: "Russia",
    niceName: "Krasnoyarsk, Russia",
    timezone: "Asia/Krasnoyarsk",
  },
  {
    city: "Kuala Lumpur",
    country: "Malaysia",
    niceName: "Kuala Lumpur, Malaysia",
    timezone: "Asia/Kuala_Lumpur",
  },
  {
    city: "Kuching",
    country: "Malaysia",
    niceName: "Kuching, Malaysia",
    timezone: "Asia/Kuching",
  },
  {
    city: "Kuwait",
    country: "Kuwait",
    niceName: "Kuwait, Kuwait",
    timezone: "Asia/Kuwait",
  },
  {
    city: "Macao",
    country: "China",
    niceName: "Macao, China",
    timezone: "Asia/Macao",
  },
  {
    city: "Macau",
    country: "Macao",
    niceName: "Macau, Macao",
    timezone: "Asia/Macau",
  },
  {
    city: "Magadan",
    country: "Russia",
    niceName: "Magadan, Russia",
    timezone: "Asia/Magadan",
  },
  {
    city: "Makassar",
    country: "Indonesia",
    niceName: "Makassar, Indonesia",
    timezone: "Asia/Makassar",
  },
  {
    city: "Manila",
    country: "Philippines",
    niceName: "Manila, Philippines",
    timezone: "Asia/Manila",
  },
  {
    city: "Muscat",
    country: "Oman",
    niceName: "Muscat, Oman",
    timezone: "Asia/Muscat",
  },
  {
    city: "Novokuznetsk",
    country: "Russia",
    niceName: "Novokuznetsk, Russia",
    timezone: "Asia/Novokuznetsk",
  },
  {
    city: "Novosibirsk",
    country: "Russia",
    niceName: "Novosibirsk, Russia",
    timezone: "Asia/Novosibirsk",
  },
  {
    city: "Omsk",
    country: "Russia",
    niceName: "Omsk, Russia",
    timezone: "Asia/Omsk",
  },
  {
    city: "Oral",
    country: "Kazakhstan",
    niceName: "Oral, Kazakhstan",
    timezone: "Asia/Oral",
  },
  {
    city: "Phnom Penh",
    country: "Cambodia",
    niceName: "Phnom Penh, Cambodia",
    timezone: "Asia/Phnom_Penh",
  },
  {
    city: "Pontianak",
    country: "Indonesia",
    niceName: "Pontianak, Indonesia",
    timezone: "Asia/Pontianak",
  },
  {
    city: "Pyongyang",
    country: "North Korea",
    niceName: "Pyongyang, North Korea",
    timezone: "Asia/Pyongyang",
  },
  {
    city: "Qatar",
    country: "Qatar",
    niceName: "Qatar, Qatar",
    timezone: "Asia/Qatar",
  },
  {
    city: "Qyzylorda",
    country: "Kazakhstan",
    niceName: "Qyzylorda, Kazakhstan",
    timezone: "Asia/Qyzylorda",
  },
  {
    city: "Rangoon",
    country: "Myanmar",
    niceName: "Rangoon, Myanmar",
    timezone: "Asia/Rangoon",
  },
  {
    city: "Riyadh",
    country: "Saudi Arabia",
    niceName: "Riyadh, Saudi Arabia",
    timezone: "Asia/Riyadh",
  },
  {
    city: "Saigon",
    country: "Viet Nam",
    niceName: "Saigon, Viet Nam",
    timezone: "Asia/Saigon",
  },
  {
    city: "Sakhalin",
    country: "Russia",
    niceName: "Sakhalin, Russia",
    timezone: "Asia/Sakhalin",
  },
  {
    city: "Samarkand",
    country: "Uzbekistan",
    niceName: "Samarkand, Uzbekistan",
    timezone: "Asia/Samarkand",
  },
  {
    city: "Seoul",
    country: "South Korea",
    niceName: "Seoul, South Korea",
    timezone: "Asia/Seoul",
  },
  {
    city: "Shanghai",
    country: "China",
    niceName: "Shanghai, China",
    timezone: "Asia/Shanghai",
  },
  {
    city: "Singapore",
    country: "Singapore",
    niceName: "Singapore, Singapore",
    timezone: "Asia/Singapore",
  },
  {
    city: "Srednekolymsk",
    country: "Russia",
    niceName: "Srednekolymsk, Russia",
    timezone: "Asia/Srednekolymsk",
  },
  {
    city: "Taipei",
    country: "Taiwan",
    niceName: "Taipei, Taiwan",
    timezone: "Asia/Taipei",
  },
  {
    city: "Tashkent",
    country: "Uzbekistan",
    niceName: "Tashkent, Uzbekistan",
    timezone: "Asia/Tashkent",
  },
  {
    city: "Tbilisi",
    country: "Georgia",
    niceName: "Tbilisi, Georgia",
    timezone: "Asia/Tbilisi",
  },
  {
    city: "Tehran",
    country: "Iran",
    niceName: "Tehran, Iran",
    timezone: "Asia/Tehran",
  },
  {
    city: "Tel Aviv",
    country: "Israel",
    niceName: "Tel Aviv, Israel",
    timezone: "Asia/Tel_Aviv",
  },
  {
    city: "Thimbu",
    country: "Bhutan",
    niceName: "Thimbu, Bhutan",
    timezone: "Asia/Thimbu",
  },
  {
    city: "Thimphu",
    country: "Bhutan",
    niceName: "Thimphu, Bhutan",
    timezone: "Asia/Thimphu",
  },
  {
    city: "Tokyo",
    country: "Japan",
    niceName: "Tokyo, Japan",
    timezone: "Asia/Tokyo",
  },
  {
    city: "Tomsk",
    country: "Russia",
    niceName: "Tomsk, Russia",
    timezone: "Asia/Tomsk",
  },
  {
    city: "Ujung Pandang",
    country: "Indonesia",
    niceName: "Ujung Pandang, Indonesia",
    timezone: "Asia/Ujung_Pandang",
  },
  {
    city: "Ulaanbaatar",
    country: "Mongolia",
    niceName: "Ulaanbaatar, Mongolia",
    timezone: "Asia/Ulaanbaatar",
  },
  {
    city: "Ulan Bator",
    country: "Mongolia",
    niceName: "Ulan Bator, Mongolia",
    timezone: "Asia/Ulan_Bator",
  },
  {
    city: "Urumqi",
    country: "China",
    niceName: "Urumqi, China",
    timezone: "Asia/Urumqi",
  },
  {
    city: "Ust-Nera",
    country: "Russia",
    niceName: "Ust-Nera, Russia",
    timezone: "Asia/Ust-Nera",
  },
  {
    city: "Vientiane",
    country: "Laos",
    niceName: "Vientiane, Laos",
    timezone: "Asia/Vientiane",
  },
  {
    city: "Vladivostok",
    country: "Russia",
    niceName: "Vladivostok, Russia",
    timezone: "Asia/Vladivostok",
  },
  {
    city: "Yakutsk",
    country: "Russia",
    niceName: "Yakutsk, Russia",
    timezone: "Asia/Yakutsk",
  },
  {
    city: "Yangon",
    country: "Myanmar",
    niceName: "Yangon, Myanmar",
    timezone: "Asia/Yangon",
  },
  {
    city: "Yekaterinburg",
    country: "Russia",
    niceName: "Yekaterinburg, Russia",
    timezone: "Asia/Yekaterinburg",
  },
  {
    city: "Yerevan",
    country: "Armenia",
    niceName: "Yerevan, Armenia",
    timezone: "Asia/Yerevan",
  },
  {
    city: "Azores",
    country: "Portugal",
    niceName: "Azores, Portugal",
    timezone: "Atlantic/Azores",
  },
  {
    city: "Bermuda",
    country: "Bermuda",
    niceName: "Bermuda, Bermuda",
    timezone: "Atlantic/Bermuda",
  },
  {
    city: "Canary",
    country: "Spain",
    niceName: "Canary, Spain",
    timezone: "Atlantic/Canary",
  },
  {
    city: "Cape Verde",
    country: "Cabo Verde",
    niceName: "Cape Verde, Cabo Verde",
    timezone: "Atlantic/Cape_Verde",
  },
  {
    city: "Faeroe",
    country: "Faroe Islands",
    niceName: "Faeroe, Faroe Islands",
    timezone: "Atlantic/Faeroe",
  },
  {
    city: "Faroe",
    country: "Faroe Islands",
    niceName: "Faroe, Faroe Islands",
    timezone: "Atlantic/Faroe",
  },
  {
    city: "Jan Mayen",
    country: "Svalbard and Jan Mayen",
    niceName: "Jan Mayen, Svalbard and Jan Mayen",
    timezone: "Atlantic/Jan_Mayen",
  },
  {
    city: "Madeira",
    country: "Portugal",
    niceName: "Madeira, Portugal",
    timezone: "Atlantic/Madeira",
  },
  {
    city: "Reykjavik",
    country: "Iceland",
    niceName: "Reykjavik, Iceland",
    timezone: "Atlantic/Reykjavik",
  },
  {
    city: "South Georgia",
    country: "South Georgia and the South Sandwich Islands",
    niceName: "South Georgia, South Georgia and the South Sandwich Islands",
    timezone: "Atlantic/South_Georgia",
  },
  {
    city: "St Helena",
    country: "Saint Helena, Ascension and Tristan da Cunha",
    niceName: "St Helena, Saint Helena, Ascension and Tristan da Cunha",
    timezone: "Atlantic/St_Helena",
  },
  {
    city: "Stanley",
    country: "Falkland Islands (Malvinas)",
    niceName: "Stanley, Falkland Islands (Malvinas)",
    timezone: "Atlantic/Stanley",
  },
  {
    city: "Adelaide",
    country: "Australia",
    niceName: "Adelaide, Australia",
    timezone: "Australia/Adelaide",
  },
  {
    city: "Brisbane",
    country: "Australia",
    niceName: "Brisbane, Australia",
    timezone: "Australia/Brisbane",
  },
  {
    city: "Broken Hill",
    country: "Australia",
    niceName: "Broken Hill, Australia",
    timezone: "Australia/Broken_Hill",
  },
  {
    city: "Canberra",
    country: "Australia",
    niceName: "Canberra, Australia",
    timezone: "Australia/Canberra",
  },
  {
    city: "Currie",
    country: "Australia",
    niceName: "Currie, Australia",
    timezone: "Australia/Currie",
  },
  {
    city: "Darwin",
    country: "Australia",
    niceName: "Darwin, Australia",
    timezone: "Australia/Darwin",
  },
  {
    city: "Eucla",
    country: "Australia",
    niceName: "Eucla, Australia",
    timezone: "Australia/Eucla",
  },
  {
    city: "Hobart",
    country: "Australia",
    niceName: "Hobart, Australia",
    timezone: "Australia/Hobart",
  },
  {
    city: "Lindeman",
    country: "Australia",
    niceName: "Lindeman, Australia",
    timezone: "Australia/Lindeman",
  },
  {
    city: "Lord Howe",
    country: "Australia",
    niceName: "Lord Howe, Australia",
    timezone: "Australia/Lord_Howe",
  },
  {
    city: "Melbourne",
    country: "Australia",
    niceName: "Melbourne, Australia",
    timezone: "Australia/Melbourne",
  },
  {
    city: "North",
    country: "Australia",
    niceName: "North, Australia",
    timezone: "Australia/North",
  },
  {
    city: "Perth",
    country: "Australia",
    niceName: "Perth, Australia",
    timezone: "Australia/Perth",
  },
  {
    city: "Queensland",
    country: "Australia",
    niceName: "Queensland, Australia",
    timezone: "Australia/Queensland",
  },
  {
    city: "South",
    country: "Australia",
    niceName: "South, Australia",
    timezone: "Australia/South",
  },
  {
    city: "Sydney",
    country: "Australia",
    niceName: "Sydney, Australia",
    timezone: "Australia/Sydney",
  },
  {
    city: "Tasmania",
    country: "Australia",
    niceName: "Tasmania, Australia",
    timezone: "Australia/Tasmania",
  },
  {
    city: "Victoria",
    country: "Australia",
    niceName: "Victoria, Australia",
    timezone: "Australia/Victoria",
  },
  {
    city: "West",
    country: "Australia",
    niceName: "West, Australia",
    timezone: "Australia/West",
  },
  {
    city: "Yancowinna",
    country: "Australia",
    niceName: "Yancowinna, Australia",
    timezone: "Australia/Yancowinna",
  },
  {
    city: "Acre",
    country: "Brazil",
    niceName: "Acre, Brazil",
    timezone: "Brazil/Acre",
  },
  {
    city: "East",
    country: "Brazil",
    niceName: "East, Brazil",
    timezone: "Brazil/East",
  },
  {
    city: "West",
    country: "Brazil",
    niceName: "West, Brazil",
    timezone: "Brazil/West",
  },
  {
    city: "Atlantic",
    country: "Canada",
    niceName: "Atlantic, Canada",
    timezone: "Canada/Atlantic",
  },
  {
    city: "Central",
    country: "Canada",
    niceName: "Central, Canada",
    timezone: "Canada/Central",
  },
  {
    city: "Eastern",
    country: "Canada",
    niceName: "Eastern, Canada",
    timezone: "Canada/Eastern",
  },
  {
    city: "Mountain",
    country: "Canada",
    niceName: "Mountain, Canada",
    timezone: "Canada/Mountain",
  },
  {
    city: "Newfoundland",
    country: "Canada",
    niceName: "Newfoundland, Canada",
    timezone: "Canada/Newfoundland",
  },
  {
    city: "Pacific",
    country: "Canada",
    niceName: "Pacific, Canada",
    timezone: "Canada/Pacific",
  },
  {
    city: "Saskatchewan",
    country: "Canada",
    niceName: "Saskatchewan, Canada",
    timezone: "Canada/Saskatchewan",
  },
  {
    city: "Yukon",
    country: "Canada",
    niceName: "Yukon, Canada",
    timezone: "Canada/Yukon",
  },
  {
    city: "Continental",
    country: "Chile",
    niceName: "Continental, Chile",
    timezone: "Chile/Continental",
  },
  { city: "GMT", niceName: "GMT", timezone: "Etc/GMT" },
  { city: "GMT+0", niceName: "GMT+0", timezone: "Etc/GMT+0" },
  { city: "GMT+1", niceName: "GMT+1", timezone: "Etc/GMT+1" },
  { city: "GMT+10", niceName: "GMT+10", timezone: "Etc/GMT+10" },
  { city: "GMT+11", niceName: "GMT+11", timezone: "Etc/GMT+11" },
  { city: "GMT+12", niceName: "GMT+12", timezone: "Etc/GMT+12" },
  { city: "GMT+2", niceName: "GMT+2", timezone: "Etc/GMT+2" },
  { city: "GMT+3", niceName: "GMT+3", timezone: "Etc/GMT+3" },
  { city: "GMT+4", niceName: "GMT+4", timezone: "Etc/GMT+4" },
  { city: "GMT+5", niceName: "GMT+5", timezone: "Etc/GMT+5" },
  { city: "GMT+6", niceName: "GMT+6", timezone: "Etc/GMT+6" },
  { city: "GMT+7", niceName: "GMT+7", timezone: "Etc/GMT+7" },
  { city: "GMT+8", niceName: "GMT+8", timezone: "Etc/GMT+8" },
  { city: "GMT+9", niceName: "GMT+9", timezone: "Etc/GMT+9" },
  { city: "GMT-0", niceName: "GMT-0", timezone: "Etc/GMT-0" },
  { city: "GMT-1", niceName: "GMT-1", timezone: "Etc/GMT-1" },
  { city: "GMT-10", niceName: "GMT-10", timezone: "Etc/GMT-10" },
  { city: "GMT-11", niceName: "GMT-11", timezone: "Etc/GMT-11" },
  { city: "GMT-12", niceName: "GMT-12", timezone: "Etc/GMT-12" },
  { city: "GMT-13", niceName: "GMT-13", timezone: "Etc/GMT-13" },
  { city: "GMT-14", niceName: "GMT-14", timezone: "Etc/GMT-14" },
  { city: "GMT-2", niceName: "GMT-2", timezone: "Etc/GMT-2" },
  { city: "GMT-3", niceName: "GMT-3", timezone: "Etc/GMT-3" },
  { city: "GMT-4", niceName: "GMT-4", timezone: "Etc/GMT-4" },
  { city: "GMT-5", niceName: "GMT-5", timezone: "Etc/GMT-5" },
  { city: "GMT-6", niceName: "GMT-6", timezone: "Etc/GMT-6" },
  { city: "GMT-7", niceName: "GMT-7", timezone: "Etc/GMT-7" },
  { city: "GMT-8", niceName: "GMT-8", timezone: "Etc/GMT-8" },
  { city: "GMT-9", niceName: "GMT-9", timezone: "Etc/GMT-9" },
  {
    city: "Greenwich",
    country: "United Kingdom",
    niceName: "Greenwich, United Kingdom",
    timezone: "Etc/Greenwich",
  },
  {
    city: "Universal",

    niceName: "Universal",
    timezone: "Etc/Universal",
  },
  { city: "UTC", niceName: "UTC", timezone: "Etc/UTC" },
  {
    city: "Zulu",
    country: "South Africa",
    niceName: "Zulu, South Africa",
    timezone: "Etc/Zulu",
  },
  {
    city: "Amsterdam",
    country: "Netherlands",
    niceName: "Amsterdam, Netherlands",
    timezone: "Europe/Amsterdam",
  },
  {
    city: "Andorra",
    country: "Andorra",
    niceName: "Andorra, Andorra",
    timezone: "Europe/Andorra",
  },
  {
    city: "Astrakhan",
    country: "Russia",
    niceName: "Astrakhan, Russia",
    timezone: "Europe/Astrakhan",
  },
  {
    city: "Athens",
    country: "Greece",
    niceName: "Athens, Greece",
    timezone: "Europe/Athens",
  },
  {
    city: "Belfast",
    country: "United Kingdom",
    niceName: "Belfast, United Kingdom",
    timezone: "Europe/Belfast",
  },
  {
    city: "Belgrade",
    country: "Serbia",
    niceName: "Belgrade, Serbia",
    timezone: "Europe/Belgrade",
  },
  {
    city: "Berlin",
    country: "Germany",
    niceName: "Berlin, Germany",
    timezone: "Europe/Berlin",
  },
  {
    city: "Bratislava",
    country: "Slovakia",
    niceName: "Bratislava, Slovakia",
    timezone: "Europe/Bratislava",
  },
  {
    city: "Brussels",
    country: "Belgium",
    niceName: "Brussels, Belgium",
    timezone: "Europe/Brussels",
  },
  {
    city: "Bucharest",
    country: "Romania",
    niceName: "Bucharest, Romania",
    timezone: "Europe/Bucharest",
  },
  {
    city: "Budapest",
    country: "Hungary",
    niceName: "Budapest, Hungary",
    timezone: "Europe/Budapest",
  },
  {
    city: "Busingen",
    country: "Germany",
    niceName: "Busingen, Germany",
    timezone: "Europe/Busingen",
  },
  {
    city: "Chisinau",
    country: "Moldova",
    niceName: "Chisinau, Moldova",
    timezone: "Europe/Chisinau",
  },
  {
    city: "Copenhagen",
    country: "Denmark",
    niceName: "Copenhagen, Denmark",
    timezone: "Europe/Copenhagen",
  },
  {
    city: "Dublin",
    country: "Ireland",
    niceName: "Dublin, Ireland",
    timezone: "Europe/Dublin",
  },
  {
    city: "Gibraltar",
    country: "Gibraltar",
    niceName: "Gibraltar, Gibraltar",
    timezone: "Europe/Gibraltar",
  },
  {
    city: "Guernsey",
    country: "Guernsey",
    niceName: "Guernsey, Guernsey",
    timezone: "Europe/Guernsey",
  },
  {
    city: "Helsinki",
    country: "Finland",
    niceName: "Helsinki, Finland",
    timezone: "Europe/Helsinki",
  },
  {
    city: "Isle of Man",
    country: "Isle of Man",
    niceName: "Isle of Man, Isle of Man",
    timezone: "Europe/Isle_of_Man",
  },
  {
    city: "Jersey",
    country: "Jersey",
    niceName: "Jersey, Jersey",
    timezone: "Europe/Jersey",
  },
  {
    city: "Kaliningrad",
    country: "Russia",
    niceName: "Kaliningrad, Russia",
    timezone: "Europe/Kaliningrad",
  },
  {
    city: "Kiev",
    country: "Ukraine",
    niceName: "Kiev, Ukraine",
    timezone: "Europe/Kiev",
  },
  {
    city: "Kirov",
    country: "Russia",
    niceName: "Kirov, Russia",
    timezone: "Europe/Kirov",
  },
  {
    city: "Lisbon",
    country: "Portugal",
    niceName: "Lisbon, Portugal",
    timezone: "Europe/Lisbon",
  },
  {
    city: "Ljubljana",
    country: "Slovenia",
    niceName: "Ljubljana, Slovenia",
    timezone: "Europe/Ljubljana",
  },
  {
    city: "London",
    country: "United Kingdom",
    niceName: "London, United Kingdom",
    timezone: "Europe/London",
  },
  {
    city: "Luxembourg",
    country: "Luxembourg",
    niceName: "Luxembourg, Luxembourg",
    timezone: "Europe/Luxembourg",
  },
  {
    city: "Madrid",
    country: "Spain",
    niceName: "Madrid, Spain",
    timezone: "Europe/Madrid",
  },
  {
    city: "Malta",
    country: "Malta",
    niceName: "Malta, Malta",
    timezone: "Europe/Malta",
  },
  {
    city: "Mariehamn",
    country: "Åland Islands",
    niceName: "Mariehamn, Åland Islands",
    timezone: "Europe/Mariehamn",
  },
  {
    city: "Minsk",
    country: "Belarus",
    niceName: "Minsk, Belarus",
    timezone: "Europe/Minsk",
  },
  {
    city: "Monaco",
    country: "Monaco",
    niceName: "Monaco, Monaco",
    timezone: "Europe/Monaco",
  },
  {
    city: "Moscow",
    country: "Russia",
    niceName: "Moscow, Russia",
    timezone: "Europe/Moscow",
  },
  {
    city: "Nicosia",
    country: "Cyprus",
    niceName: "Nicosia, Cyprus",
    timezone: "Europe/Nicosia",
  },
  {
    city: "Oslo",
    country: "Norway",
    niceName: "Oslo, Norway",
    timezone: "Europe/Oslo",
  },
  {
    city: "Paris",
    country: "France",
    niceName: "Paris, France",
    timezone: "Europe/Paris",
  },
  {
    city: "Podgorica",
    country: "Montenegro",
    niceName: "Podgorica, Montenegro",
    timezone: "Europe/Podgorica",
  },
  {
    city: "Prague",
    country: "Czechia",
    niceName: "Prague, Czechia",
    timezone: "Europe/Prague",
  },
  {
    city: "Riga",
    country: "Latvia",
    niceName: "Riga, Latvia",
    timezone: "Europe/Riga",
  },
  {
    city: "Rome",
    country: "Italy",
    niceName: "Rome, Italy",
    timezone: "Europe/Rome",
  },
  {
    city: "Samara",
    country: "Russia",
    niceName: "Samara, Russia",
    timezone: "Europe/Samara",
  },
  {
    city: "San Marino",
    country: "San Marino",
    niceName: "San Marino, San Marino",
    timezone: "Europe/San_Marino",
  },
  {
    city: "Sarajevo",
    country: "Bosnia and Herzegovina",
    niceName: "Sarajevo, Bosnia and Herzegovina",
    timezone: "Europe/Sarajevo",
  },
  {
    city: "Saratov",
    country: "Russia",
    niceName: "Saratov, Russia",
    timezone: "Europe/Saratov",
  },
  {
    city: "Simferopol",
    country: "Ukraine",
    niceName: "Simferopol, Ukraine",
    timezone: "Europe/Simferopol",
  },
  {
    city: "Skopje",
    country: "Macedonia",
    niceName: "Skopje, Macedonia",
    timezone: "Europe/Skopje",
  },
  {
    city: "Sofia",
    country: "Bulgaria",
    niceName: "Sofia, Bulgaria",
    timezone: "Europe/Sofia",
  },
  {
    city: "Stockholm",
    country: "Sweden",
    niceName: "Stockholm, Sweden",
    timezone: "Europe/Stockholm",
  },
  {
    city: "Tallinn",
    country: "Estonia",
    niceName: "Tallinn, Estonia",
    timezone: "Europe/Tallinn",
  },
  {
    city: "Tirane",
    country: "Albania",
    niceName: "Tirane, Albania",
    timezone: "Europe/Tirane",
  },
  {
    city: "Tiraspol",

    niceName: "Tiraspol",
    timezone: "Europe/Tiraspol",
  },
  {
    city: "Ulyanovsk",
    country: "Russia",
    niceName: "Ulyanovsk, Russia",
    timezone: "Europe/Ulyanovsk",
  },
  {
    city: "Uzhgorod",
    country: "Ukraine",
    niceName: "Uzhgorod, Ukraine",
    timezone: "Europe/Uzhgorod",
  },
  {
    city: "Vaduz",
    country: "Liechtenstein",
    niceName: "Vaduz, Liechtenstein",
    timezone: "Europe/Vaduz",
  },
  {
    city: "Vatican",
    country: "Holy See",
    niceName: "Vatican, Holy See",
    timezone: "Europe/Vatican",
  },
  {
    city: "Vienna",
    country: "Austria",
    niceName: "Vienna, Austria",
    timezone: "Europe/Vienna",
  },
  {
    city: "Vilnius",
    country: "Lithuania",
    niceName: "Vilnius, Lithuania",
    timezone: "Europe/Vilnius",
  },
  {
    city: "Volgograd",
    country: "Russia",
    niceName: "Volgograd, Russia",
    timezone: "Europe/Volgograd",
  },
  {
    city: "Warsaw",
    country: "Poland",
    niceName: "Warsaw, Poland",
    timezone: "Europe/Warsaw",
  },
  {
    city: "Zagreb",
    country: "Croatia",
    niceName: "Zagreb, Croatia",
    timezone: "Europe/Zagreb",
  },
  {
    city: "Zaporozhye",
    country: "Ukraine",
    niceName: "Zaporozhye, Ukraine",
    timezone: "Europe/Zaporozhye",
  },
  {
    city: "Zurich",
    country: "Switzerland",
    niceName: "Zurich, Switzerland",
    timezone: "Europe/Zurich",
  },
  {
    city: "Antananarivo",
    country: "Madagascar",
    niceName: "Antananarivo, Madagascar",
    timezone: "Indian/Antananarivo",
  },
  {
    city: "Chagos",
    country: "British Indian Ocean Territory",
    niceName: "Chagos, British Indian Ocean Territory",
    timezone: "Indian/Chagos",
  },
  {
    city: "Christmas",
    country: "Christmas Island",
    niceName: "Christmas, Christmas Island",
    timezone: "Indian/Christmas",
  },
  {
    city: "Cocos",
    country: "Cocos (Keeling) Islands",
    niceName: "Cocos, Cocos (Keeling) Islands",
    timezone: "Indian/Cocos",
  },
  {
    city: "Comoro",
    country: "Comoros",
    niceName: "Comoro, Comoros",
    timezone: "Indian/Comoro",
  },
  {
    city: "Kerguelen",
    country: "French Southern Territories",
    niceName: "Kerguelen, French Southern Territories",
    timezone: "Indian/Kerguelen",
  },
  {
    city: "Mahe",
    country: "Seychelles",
    niceName: "Mahe, Seychelles",
    timezone: "Indian/Mahe",
  },
  {
    city: "Maldives",
    country: "Maldives",
    niceName: "Maldives, Maldives",
    timezone: "Indian/Maldives",
  },
  {
    city: "Mauritius",
    country: "Mauritius",
    niceName: "Mauritius, Mauritius",
    timezone: "Indian/Mauritius",
  },
  {
    city: "Mayotte",
    country: "Mayotte",
    niceName: "Mayotte, Mayotte",
    timezone: "Indian/Mayotte",
  },
  {
    city: "Reunion",
    country: "Réunion",
    niceName: "Reunion, Réunion",
    timezone: "Indian/Reunion",
  },
  {
    city: "General",
    country: "Mexico",
    niceName: "General, Mexico",
    timezone: "Mexico/General",
  },
  {
    city: "Apia",
    country: "Samoa",
    niceName: "Apia, Samoa",
    timezone: "Pacific/Apia",
  },
  {
    city: "Auckland",
    country: "New Zealand",
    niceName: "Auckland, New Zealand",
    timezone: "Pacific/Auckland",
  },
  {
    city: "Bougainville",
    country: "Papua New Guinea",
    niceName: "Bougainville, Papua New Guinea",
    timezone: "Pacific/Bougainville",
  },
  {
    city: "Chatham",
    country: "New Zealand",
    niceName: "Chatham, New Zealand",
    timezone: "Pacific/Chatham",
  },
  {
    city: "Chuuk",
    country: "Micronesia",
    niceName: "Chuuk, Micronesia",
    timezone: "Pacific/Chuuk",
  },
  {
    city: "Easter",
    country: "Chile",
    niceName: "Easter, Chile",
    timezone: "Pacific/Easter",
  },
  {
    city: "Efate",
    country: "Vanuatu",
    niceName: "Efate, Vanuatu",
    timezone: "Pacific/Efate",
  },
  {
    city: "Enderbury",
    country: "Kiribati",
    niceName: "Enderbury, Kiribati",
    timezone: "Pacific/Enderbury",
  },
  {
    city: "Fakaofo",
    country: "Tokelau",
    niceName: "Fakaofo, Tokelau",
    timezone: "Pacific/Fakaofo",
  },
  {
    city: "Fiji",
    country: "Fiji",
    niceName: "Fiji, Fiji",
    timezone: "Pacific/Fiji",
  },
  {
    city: "Funafuti",
    country: "Tuvalu",
    niceName: "Funafuti, Tuvalu",
    timezone: "Pacific/Funafuti",
  },
  {
    city: "Galapagos",
    country: "Ecuador",
    niceName: "Galapagos, Ecuador",
    timezone: "Pacific/Galapagos",
  },
  {
    city: "Gambier",
    country: "French Polynesia",
    niceName: "Gambier, French Polynesia",
    timezone: "Pacific/Gambier",
  },
  {
    city: "Guadalcanal",
    country: "Solomon Islands",
    niceName: "Guadalcanal, Solomon Islands",
    timezone: "Pacific/Guadalcanal",
  },
  {
    city: "Guam",
    country: "Guam",
    niceName: "Guam, Guam",
    timezone: "Pacific/Guam",
  },
  {
    city: "Honolulu",
    country: "United States of America",
    niceName: "Honolulu, United States of America",
    timezone: "Pacific/Honolulu",
  },
  {
    city: "Johnston",
    country: "United States of America",
    niceName: "Johnston, United States of America",
    timezone: "Pacific/Johnston",
  },
  {
    city: "Kiritimati",
    country: "Kiribati",
    niceName: "Kiritimati, Kiribati",
    timezone: "Pacific/Kiritimati",
  },
  {
    city: "Kosrae",
    country: "Micronesia",
    niceName: "Kosrae, Micronesia",
    timezone: "Pacific/Kosrae",
  },
  {
    city: "Kwajalein",
    country: "Marshall Islands",
    niceName: "Kwajalein, Marshall Islands",
    timezone: "Pacific/Kwajalein",
  },
  {
    city: "Majuro",
    country: "Marshall Islands",
    niceName: "Majuro, Marshall Islands",
    timezone: "Pacific/Majuro",
  },
  {
    city: "Marquesas",
    country: "French Polynesia",
    niceName: "Marquesas, French Polynesia",
    timezone: "Pacific/Marquesas",
  },
  {
    city: "Midway",
    country: "United States Minor Outlying Islands",
    niceName: "Midway, United States Minor Outlying Islands",
    timezone: "Pacific/Midway",
  },
  {
    city: "Nauru",
    country: "Nauru",
    niceName: "Nauru, Nauru",
    timezone: "Pacific/Nauru",
  },
  {
    city: "Niue",
    country: "Niue",
    niceName: "Niue, Niue",
    timezone: "Pacific/Niue",
  },
  {
    city: "Norfolk",
    country: "Norfolk Island",
    niceName: "Norfolk, Norfolk Island",
    timezone: "Pacific/Norfolk",
  },
  {
    city: "Noumea",
    country: "New Caledonia",
    niceName: "Noumea, New Caledonia",
    timezone: "Pacific/Noumea",
  },
  {
    city: "Pago Pago",
    country: "American Samoa",
    niceName: "Pago Pago, American Samoa",
    timezone: "Pacific/Pago_Pago",
  },
  {
    city: "Palau",
    country: "Palau",
    niceName: "Palau, Palau",
    timezone: "Pacific/Palau",
  },
  {
    city: "Pitcairn",
    country: "Pitcairn",
    niceName: "Pitcairn, Pitcairn",
    timezone: "Pacific/Pitcairn",
  },
  {
    city: "Pohnpei",
    country: "Micronesia",
    niceName: "Pohnpei, Micronesia",
    timezone: "Pacific/Pohnpei",
  },
  {
    city: "Ponape",
    country: "Micronesia",
    niceName: "Ponape, Micronesia",
    timezone: "Pacific/Ponape",
  },
  {
    city: "Port Moresby",
    country: "Papua New Guinea",
    niceName: "Port Moresby, Papua New Guinea",
    timezone: "Pacific/Port_Moresby",
  },
  {
    city: "Rarotonga",
    country: "Cook Islands",
    niceName: "Rarotonga, Cook Islands",
    timezone: "Pacific/Rarotonga",
  },
  {
    city: "Saipan",
    country: "Northern Mariana Islands",
    niceName: "Saipan, Northern Mariana Islands",
    timezone: "Pacific/Saipan",
  },
  {
    city: "Samoa",
    country: "Samoa",
    niceName: "Samoa, Samoa",
    timezone: "Pacific/Samoa",
  },
  {
    city: "Tahiti",
    country: "French Polynesia",
    niceName: "Tahiti, French Polynesia",
    timezone: "Pacific/Tahiti",
  },
  {
    city: "Tarawa",
    country: "Kiribati",
    niceName: "Tarawa, Kiribati",
    timezone: "Pacific/Tarawa",
  },
  {
    city: "Tongatapu",
    country: "Tonga",
    niceName: "Tongatapu, Tonga",
    timezone: "Pacific/Tongatapu",
  },
  {
    city: "Truk",
    country: "Micronesia",
    niceName: "Truk, Micronesia",
    timezone: "Pacific/Truk",
  },
  {
    city: "Wake",
    country: "United States Minor Outlying Islands",
    niceName: "Wake, United States Minor Outlying Islands",
    timezone: "Pacific/Wake",
  },
  {
    city: "Wallis",
    country: "Wallis and Futuna",
    niceName: "Wallis, Wallis and Futuna",
    timezone: "Pacific/Wallis",
  },
  {
    city: "Yap",
    country: "Micronesia",
    niceName: "Yap, Micronesia",
    timezone: "Pacific/Yap",
  },
];
